# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-20 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180920_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='my location is ...', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='my description here'),
        ),
    ]
