# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
